version: '3.8'

services:
  db:
    container_name: pokemon_db
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    environment:
      - name=value
    ports:
      - 27017:27017
    restart: always

volumes:
  poke-vol:
    external: false
