version: '3.8'

services:
  db:
    container_name: pokemon_db
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: yusep
      MONGO_INITDB_ROOT_PASSWORD: mekieros
    restart: always
    command: ['--auth']
volumes:
  poke-vol:
    external: false
