version: '3.8'

services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: always
    command: ['--auth']

  dashboard:
    depends_on:
      - db
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITHORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_NAME}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    restart: always

volumes:
  poke-vol:
    external: false
